name: cookday
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.8.2+1
  flutter_speed_dial: ^1.0.8
  barcode_scan: ^0.0.7
  carousel_slider: ^0.0.7
  firebase_auth: 
  google_sign_in: ^3.2.4
  bubble_tab_indicator: ^0.1.3
  flutter_typeahead: ^0.4.1



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/glogin.png
    - images/refrige.jpg
    - images/cookdaylogo.png
    - images/cooksplash.jpg
    - images/pancake.jpeg
    - images/mainpic.png
    - images/ingredients/seafood.png
    - images/ingredients/meat.png
    - images/ingredients/fruit.png
    - images/ingredients/dairy.png
    - images/ingredients/sauce.png
    - images/ingredients/beverage.png
    - images/ingredients/other.png
    - images/ingredients/tools.png
    - images/ingredients/009-kettle.png
    - images/appbar.png
    - images/suggest/bakery.jpg
    - images/suggest/chicken.jpg
    - images/suggest/dessert.jpg
    - images/suggest/egg.jpg
    - images/suggest/noodle.jpg
    - images/suggest/rice.jpg
    - images/suggest/salad.jpg
    - images/suggest/seafood.jpg
    - images/suggest/meat.jpg
    - images/suggest/beverage.jpg
    - images/suggest/jigae.jpg
    - images/suggest/time.jpg
    - images/suggest/fried.jpg
    - images/suggest/breakfast.jpg
  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: Hanna
      fonts:
        - asset: fonts/BMHANNAAir_ttf.ttf
    - family: Monoton
      fonts:
        - asset: fonts/Monoton-Regular.ttf
    - family: PermanentMarker
      fonts:
        - asset: fonts/PermanentMarker-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Dancing
      fonts:
        - asset: fonts/DancingScript-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
